source 'https://rubygems.org'

gem 'rspec'
gem 'rake'
gem 'activesupport'
gem 'selenium-webdriver'
gem 'json'
gem 'i18n'
gem 'pry'
gem 'pry-nav'
gem 'tzinfo'
gem 'tzinfo-data'
gem 'net-ssh'
gem 'rest-client'
gem 'net-scp'
gem 'mail'
gem 'nokogiri'